# Generated by Django 3.0.4 on 2020-03-23 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='assistance',
            name='check_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 17, 57, 20, 841467)),
        ),
    ]
